---
- name: Install LAMP server
  hosts: all
  become: yes
  tasks:

    - name: apt-get update
      shell: "apt update"


    - name: Install required packages
      package:
        name:
          - apache2
          - mysql-server
          - php
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Configure PHP
      copy:
        src: /home/index.html
        dest: /var/www/html/

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes
